# Menus
menu:
  Home: .
  Archives: archives
  Tags: tags
  About: https://mozix.ir

# Customize
customize:
    logo:
        enabled: true
        width: 40
        height: 40
        url: /images/logo.png
    profile:
        enabled: true
        gravatar: ali.moez.gholami@gmail.com
        author: Moez
        author_title: Software Engineer
        location: Austin, Texas
    highlight: monokai
    sidebar: right
    thumbnail: true
    favicon: /images/favicon.ico
    social_links:
        github: http://github.com/moezgholami
        twitter: /
    social_link_tooltip: true # enable the social link tooltip, options: true, false

# Widgets
widgets:
    - recent_posts
    - tagcloud

# Search
search:
    insight: true

# Comment
comment:
    disqus: mozix

# Share
share: default # options: jiathis, bdshare, addtoany, default

# Plugins
plugins:
    lightgallery: true # options: true, false
    justifiedgallery: true # options: true, false
    mathjax: false # options: true, false
    google_analytics: # enter the tracking ID for your Google Analytics
    google_site_verification: # enter Google site verification code

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
    links:
