# Menus
menu:
  Blog: /blog
  Archives: /blog/archives
  Tags: /blog/tags
  Contact: /contact

# Customize
customize:
    logo:
        enabled: true
        width: 40
        height: 40
        url: /images/logo.png
    profile:
        enabled: true
        gravatar: ali.moez.gholami@gmail.com
        author: Ali Moezgholami
        author_title: Software Engineer
        location: Austin, Texas
    highlight: monokai
    sidebar: right
    thumbnail: true
    favicon: /images/favicon.ico
    social_links:
        twitter: https://twitter.com/moezzgh
        linkedin: https://www.linkedin.com/in/ali-moezgholami-aa610689
        github: https://github.com/moezgholami
    social_link_tooltip: false

# Widgets
widgets:
    - recent_posts

# Search
search:
    insight: true

# Comment
comment:
    disqus: moez

# Share
share: default

# Plugins
plugins:
    lightgallery: true # options: true, false
    justifiedgallery: true # options: true, false
    mathjax: false # options: true, false
    google_analytics: # enter the tracking ID for your Google Analytics
    google_site_verification: # enter Google site verification code

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
    links:
